### ISSUE TITLE
Navbar breaks on intermediate screen size

### ISSUE THREAD

**Issue by davidjrichardson** [mjtamlyn/tamlynscore#65]
The navbar ends up breaking when the screen isn't large enough to support it full width:
![broken nav bar](http://i.imgur.com/pA9kYxx.png)

**Comment by mjtamlyn** [comment]
A possible design idea:

![](https://www.dropbox.com/s/3e17cifgoqw6lp8/Screenshot%202015-12-06%2008.34.55.png?dl=1)

- Changes spacing in top bar
- Changes h1 styles
- Adds following styles for the new menu bar
- Need to work out how to center the button labels vertically, what happens with bigger screens etc
```
nav.action-bar {
    background: #fafafa;
    border: 1px solid #eeeeee;
    display: flex;
    justify-content: space-between;
    font-size: 14px;
}

nav.action-bar a {
    height: 30px;
    position: relative;
    color: rgba(0, 6, 22, 0.9);
}

a.download:before {
    content: "\f019";
    font-family: FontAwesome;
    width: 30px;
    height: 100%;
    line-height: 30px;
    display: inline-block;
    font-size: 20px;
    margin-right: 2px;
}

a.menu:after {
    content: "\f0c9";
    font-family: FontAwesome;
    width: 30px;
    height: 100%;
    line-height: 30px;
    display: inline-block;
    font-size: 20px;
    margin-left: 2px;
}
```

**Comment by mjtamlyn** [comment]
This got kinda fixed ages ago with the photo design
